debug: disable all tests
Signed-off-by: Din Music <din.music@canonical.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -149,40 +149,40 @@ jobs:
           cd /home/runner/work/lxd/lxd-test
           make
 
-      - name: Check lxc/lxd-agent binary sizes
-        if: env.GOCOVERAGE != 'true'
-        run: |
-          set -eux
+      # - name: Check lxc/lxd-agent binary sizes
+      #   if: env.GOCOVERAGE != 'true'
+      #   run: |
+      #     set -eux
 
-          # bin/max (sizes are in MiB)
-          SIZES="lxc 16
-                 lxd-agent 14"
-          MIB="$((1024 * 1024))"
+      #     # bin/max (sizes are in MiB)
+      #     SIZES="lxc 16
+      #            lxd-agent 14"
+      #     MIB="$((1024 * 1024))"
 
-          # Strip a copy of the freshly built binaries and check their size
-          mkdir /tmp/bin
-          while read -r bin max; do
-            install --strip "/home/runner/go/bin/${bin}" /tmp/bin/
-            cur="$(stat --format=%s "/tmp/bin/${bin}")"
-            min=$((max - 1))
-            min_mib="$((min * MIB))"
-            max_mib="$((max * MIB))"
-            rm -f "/tmp/bin/${bin}"
+      #     # Strip a copy of the freshly built binaries and check their size
+      #     mkdir /tmp/bin
+      #     while read -r bin max; do
+      #       install --strip "/home/runner/go/bin/${bin}" /tmp/bin/
+      #       cur="$(stat --format=%s "/tmp/bin/${bin}")"
+      #       min=$((max - 1))
+      #       min_mib="$((min * MIB))"
+      #       max_mib="$((max * MIB))"
+      #       rm -f "/tmp/bin/${bin}"
 
-            if [ "${cur}" -gt "${max_mib}" ]; then
-              echo "FAIL: ${bin} binary size exceeds ${max}MiB"
-              exit 1
-            fi
+      #       if [ "${cur}" -gt "${max_mib}" ]; then
+      #         echo "FAIL: ${bin} binary size exceeds ${max}MiB"
+      #         exit 1
+      #       fi
 
-            # XXX: check for when we need to lower the min/max sizes
-            if [ "${cur}" -lt "${min_mib}" ]; then
-              echo "Congratulations: ${bin} binary size reduced below ${min}MiB"
-              echo "It is now time to edit the workflow job to use smaller min/max sizes for ${bin}"
-              exit 1
-            fi
+      #       # XXX: check for when we need to lower the min/max sizes
+      #       if [ "${cur}" -lt "${min_mib}" ]; then
+      #         echo "Congratulations: ${bin} binary size reduced below ${min}MiB"
+      #         echo "It is now time to edit the workflow job to use smaller min/max sizes for ${bin}"
+      #         exit 1
+      #       fi
 
-            echo "OK: ${bin} is between ${min} and ${max}MiB"
-          done <<< ${SIZES}
+      #       echo "OK: ${bin} is between ${min} and ${max}MiB"
+      #     done <<< ${SIZES}
 
       - name: Check binaries were compiled with the Go minimum version
         run: |
@@ -197,24 +197,24 @@ jobs:
             exit 1
           fi
 
-      - name: Run static analysis
-        env:
-          GITHUB_BEFORE: ${{ github.event.before }}
-        run: |
-          set -eux
-          sudo chmod o+w ./lxd/metadata/configuration.json
-          sudo chmod o+w ./doc/metadata.txt
-          sudo chmod o+w ./po/*
-          sudo chmod o+w ./lxd/auth/entitlements_generated.go
-          sudo chmod o+w ./lxd/auth/drivers/openfga_model.openfga
-          make static-analysis
+      # - name: Run static analysis
+      #   env:
+      #     GITHUB_BEFORE: ${{ github.event.before }}
+      #   run: |
+      #     set -eux
+      #     sudo chmod o+w ./lxd/metadata/configuration.json
+      #     sudo chmod o+w ./doc/metadata.txt
+      #     sudo chmod o+w ./po/*
+      #     sudo chmod o+w ./lxd/auth/entitlements_generated.go
+      #     sudo chmod o+w ./lxd/auth/drivers/openfga_model.openfga
+      #     make static-analysis
 
-      - name: Unit tests (all)
-        run: |
-          set -eux
-          chmod +x ~
-          echo "root:1000000:1000000000" | sudo tee /etc/subuid /etc/subgid
-          sudo --preserve-env=CGO_CFLAGS,CGO_LDFLAGS,CGO_LDFLAGS_ALLOW,GOCOVERDIR,PKG_CONFIG_PATH,LD_LIBRARY_PATH LD_LIBRARY_PATH=${LD_LIBRARY_PATH} env "PATH=${PATH}" make check-unit
+      # - name: Unit tests (all)
+      #   run: |
+      #     set -eux
+      #     chmod +x ~
+      #     echo "root:1000000:1000000000" | sudo tee /etc/subuid /etc/subgid
+      #     sudo --preserve-env=CGO_CFLAGS,CGO_LDFLAGS,CGO_LDFLAGS_ALLOW,GOCOVERDIR,PKG_CONFIG_PATH,LD_LIBRARY_PATH LD_LIBRARY_PATH=${LD_LIBRARY_PATH} env "PATH=${PATH}" make check-unit
 
       - name: Upload coverage data
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
